kind: ConfigMap
apiVersion: v1
metadata:
  name: trip-configs
data:
  SQL_SERVER: "sqlserverofy4959.database.windows.net"
  SQL_DBNAME: "mydrivingDB"
  WEB_PORT: "80"
  PORT: "80"
  ASPNETCORE_ENVIRONMENT: "Production"
  TRIPS_API_ENDPOINT: "http://trips"
  USERPROFILE_API_ENDPOINT: "http://userprofile"
