apiVersion: apps/v1
kind: Deployment
metadata:
  #A Deployment named tripviewer-deployment is created, indicated by the .metadata.name field.
  name: tripviewer-deployment
spec:
  replicas: 1
  #The .spec.selector field defines how the Deployment finds which Pods to manage. 
  selector:
    matchLabels:
      app: tripviewer
  #The template field contains the following sub-fields:
  #The Pods are labeled app: tripviewer using the .metadata.labels field.
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
      - name: tripviewer
        image: registryofy4959.azurecr.io/tripinsights/tripviewer:1.0
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 256Mi
