apiVersion: apps/v1
kind: Deployment
metadata:
  #A Deployment named userprofile-deployment is created, indicated by the .metadata.name field.
  name: userprofile-deployment
spec:
  replicas: 1
  #The .spec.selector field defines how the Deployment finds which Pods to manage. 
  selector:
    matchLabels:
      app: userprofile
  #The template field contains the following sub-fields:
  #The Pods are labeled app: userprofile using the .metadata.labels field.
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
      - name: userprofile
        image: registryofy4959.azurecr.io/tripinsights/userprofile:1.0
        #image: nginx:1.14.2
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 256Mi