apiVersion: v1
kind: Service
metadata:
  name: userprofile
spec:
  # When the node receives a request on the static port (30163)
  # "select pods with the label 'app' set to 'echo-hostname'"
  # and forward the request to one of them
  selector:
    app: userprofile

  ports:
    # Three types of ports for a service
    # nodePort - a static port assigned on each the node.  Access service via this external port number
    # port - port exposed internally in the cluster
    # targetPort - the container port to send requests to
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  #A Deployment named userprofile-deployment is created, indicated by the .metadata.name field.
  name: userprofile
spec:
  replicas: 1
  #The .spec.selector field defines how the Deployment finds which Pods to manage.
  selector:
    matchLabels:
      app: userprofile
  #The template field contains the following sub-fields:
  #The Pods are labeled app: userprofile using the .metadata.labels field.
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
        - name: userprofile
          image: registryofy4959.azurecr.io/tripinsights/userprofile:1.0
          #image: nginx:1.14.2
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: trip-secrets
            - configMapRef:
                name: trip-configs
          resources:
            requests:
              cpu: 250m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
